import { AlertCircle, CheckCircle2, Inbox, LoaderCircle, X } from "lucide-react";
import { cn } from "../../utils/cn";
import { IconButton } from "./Button";

const alertStyles = { success: "border-emerald-200 bg-emerald-50 text-emerald-900", warning: "border-amber-200 bg-amber-50 text-amber-900", danger: "border-rose-200 bg-rose-50 text-rose-900", info: "border-sky-200 bg-sky-50 text-sky-900" };
export function Alert({ variant = "info", title, children, className }) { const Icon = variant === "success" ? CheckCircle2 : AlertCircle; return <div className={cn("flex gap-3 rounded-xl border p-4 text-sm", alertStyles[variant], className)} role="alert"><Icon size={18} className="mt-0.5 shrink-0" /><div>{title && <p className="font-semibold">{title}</p>}<div className={title ? "mt-1 leading-6" : "leading-6"}>{children}</div></div></div>; }
export function Toast({ open, onClose, variant = "success", children }) { if (!open) return null; return <div className="fixed bottom-4 right-4 z-[70] w-[calc(100%-2rem)] max-w-sm"><Alert variant={variant} className="shadow-modal">{children}<IconButton label="Dismiss notification" size="sm" className="ml-auto -mr-2 -mt-2" onClick={onClose}><X size={16} /></IconButton></Alert></div>; }
export function EmptyState({ title = "Nothing here yet", description, action }) { return <div className="flex min-h-56 flex-col items-center justify-center rounded-2xl border border-dashed border-taste-border bg-white px-6 py-10 text-center"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100 text-slate-500"><Inbox size={21} /></span><h3 className="mt-4 text-base font-semibold text-slate-900">{title}</h3>{description && <p className="mt-1 max-w-md text-sm leading-6 text-slate-500">{description}</p>}{action && <div className="mt-5">{action}</div>}</div>; }
export function LoadingState({ label = "Loading" }) { return <div className="flex min-h-48 items-center justify-center gap-2 text-sm text-slate-500"><LoaderCircle size={18} className="animate-spin" />{label}</div>; }
export function ErrorState({ title = "Something went wrong", description, action }) { return <div className="flex min-h-48 flex-col items-center justify-center px-6 text-center"><AlertCircle size={26} className="text-rose-600" /><h3 className="mt-3 font-semibold text-slate-900">{title}</h3>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}{action && <div className="mt-4">{action}</div>}</div>; }
