import { useEffect, useMemo, useState } from "react";
import { BarChart3, Boxes, ChartNoAxesCombined, ClipboardList, TrendingUp } from "lucide-react";
import { Badge, Button, ContentCard, EmptyState, ErrorState, Input, LoadingState, Select, StatCard, StatusBadge, Table, TableBody, TableCell, TableHeader, TableRow } from "../../components/ui";
import { FilterBar, PageHeader, ResponsiveGrid, SectionHeader } from "../../components/layout/PageHeader";
import PageContainer from "../../components/layout/PageContainer";
import { getReportsData } from "../../services/reportsService";

const money = (value) => `₱${Number(value).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateFormat = new Intl.DateTimeFormat("en-PH", { dateStyle: "medium" });
const dateTimeFormat = new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" });
const reportTypes = { SALES: "Sales overview", TRANSACTIONS: "Transaction report", MENU: "Menu performance", BRANCH: "Branch comparison", INVENTORY: "Inventory summary" };

function SalesChart({ points }) {
  const width = 720; const height = 250; const pad = { top: 20, right: 18, bottom: 42, left: 60 }; const max = Math.max(...points.map((point) => point.grossSales), 1); const plot = points.map((point, index) => ({ ...point, x: pad.left + (index * (width - pad.left - pad.right)) / Math.max(points.length - 1, 1), y: pad.top + (height - pad.top - pad.bottom) - (point.grossSales / max) * (height - pad.top - pad.bottom) })); const line = plot.map((point, index) => `${index ? "L" : "M"} ${point.x} ${point.y}`).join(" ");
  if (!points.length) return <EmptyState title="No report data found" description="Completed POS sales for the selected period will appear here." />;
  return <div className="overflow-x-auto" aria-live="polite"><svg viewBox={`0 0 ${width} ${height}`} className="h-auto min-w-[560px] w-full" role="img" aria-label="Sales trend chart"><title>Gross sales by date</title>{[0, 0.5, 1].map((ratio) => { const y = pad.top + (height - pad.top - pad.bottom) * ratio; return <g key={ratio}><line x1={pad.left} x2={width - pad.right} y1={y} y2={y} stroke="#E5E7EB" strokeDasharray="4 5" /><text x={pad.left - 10} y={y + 4} textAnchor="end" className="fill-slate-400 text-[11px]">{money(Math.round(max * (1 - ratio)))}</text></g>; })}<path d={`${line} L ${plot.at(-1).x} ${height - pad.bottom} L ${plot[0].x} ${height - pad.bottom} Z`} fill="#7CE1DB" fillOpacity=".2" /><path d={line} fill="none" stroke="#63cbc5" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{plot.map((point) => <g key={point.date}><circle cx={point.x} cy={point.y} r="5" fill="white" stroke="#b85f98" strokeWidth="3" /><text x={point.x} y={height - 14} textAnchor="middle" className="fill-slate-500 text-[11px]">{dateFormat.format(new Date(point.date)).split(",")[0]}</text></g>)}</svg></div>;
}

function SalesReport({ data }) { return <><ResponsiveGrid><StatCard label="Total sales" value={money(data.summary.totalSales)} icon={TrendingUp} /><StatCard label="Transactions" value={data.summary.transactions} icon={ClipboardList} /><StatCard label="Average transaction" value={money(data.summary.averageTransaction)} icon={BarChart3} /><StatCard label="Top-selling item" value={data.summary.topItem} icon={ChartNoAxesCombined} /></ResponsiveGrid><ContentCard className="mt-7"><SectionHeader title="Sales trend" description="Completed sales grouped by date for the selected period." /><div className="mt-5"><SalesChart points={data.salesByDate} /></div></ContentCard><ContentCard className="mt-7"><SectionHeader title="Daily sales detail" description="Gross sales and transaction counts by date." />{data.salesByDate.length ? <div className="mt-5"><Table><TableHeader><TableRow><TableCell as="th">Date</TableCell><TableCell as="th">Transactions</TableCell><TableCell as="th">Gross sales</TableCell><TableCell as="th">Average transaction</TableCell><TableCell as="th">Branch</TableCell></TableRow></TableHeader><TableBody>{data.salesByDate.map((row) => <TableRow key={row.date}><TableCell>{dateFormat.format(new Date(row.date))}</TableCell><TableCell>{row.transactions}</TableCell><TableCell className="font-semibold">{money(row.grossSales)}</TableCell><TableCell>{money(row.grossSales / row.transactions)}</TableCell><TableCell>{row.branch}</TableCell></TableRow>)}</TableBody></Table></div> : <div className="mt-5"><EmptyState title="No report data found" description="Try adjusting the selected period or branch." /></div>}</ContentCard></>; }

function TransactionsReport({ data }) { return <ContentCard><SectionHeader title="Transaction report" description={`${data.transactions.length} completed transaction${data.transactions.length === 1 ? "" : "s"} in the selected range.`} />{data.transactions.length ? <div className="mt-5"><Table><TableHeader><TableRow><TableCell as="th">Transaction</TableCell><TableCell as="th">Date / time</TableCell><TableCell as="th">Branch</TableCell><TableCell as="th">Staff</TableCell><TableCell as="th">Items</TableCell><TableCell as="th">Payment</TableCell><TableCell as="th">Total</TableCell><TableCell as="th">Status</TableCell></TableRow></TableHeader><TableBody>{data.transactions.map((transaction) => <TableRow key={transaction.id}><TableCell className="font-semibold text-slate-900">{transaction.transactionId}</TableCell><TableCell>{dateTimeFormat.format(new Date(transaction.createdAt))}</TableCell><TableCell>{data.branches.find((branch) => branch.id === transaction.branchId)?.name ?? transaction.branchId}</TableCell><TableCell>{transaction.cashierName}</TableCell><TableCell>{transaction.items.reduce((sum, item) => sum + item.quantity, 0)}</TableCell><TableCell>{transaction.paymentMethod === "GCASH" ? "GCash / E-wallet" : "Cash"}</TableCell><TableCell className="font-semibold">{money(transaction.total)}</TableCell><TableCell><StatusBadge status="completed" /></TableCell></TableRow>)}</TableBody></Table></div> : <div className="mt-5"><EmptyState title="No report data found" description="Try adjusting the selected period or branch." /></div>}</ContentCard>; }

function MenuReport({ data }) { return <ContentCard><SectionHeader title="Menu performance" description="Items ranked by quantity sold in the selected period." />{data.menuPerformance.length ? <div className="mt-5"><Table><TableHeader><TableRow><TableCell as="th">Item</TableCell><TableCell as="th">Category</TableCell><TableCell as="th">Quantity sold</TableCell><TableCell as="th">Sales amount</TableCell><TableCell as="th">Average selling price</TableCell><TableCell as="th">Availability</TableCell></TableRow></TableHeader><TableBody>{data.menuPerformance.map((item) => <TableRow key={item.id}><TableCell className="font-semibold text-slate-900">{item.item}</TableCell><TableCell>{item.category}</TableCell><TableCell>{item.quantitySold}</TableCell><TableCell className="font-semibold">{money(item.salesAmount)}</TableCell><TableCell>{money(item.unitPrice)}</TableCell><TableCell><StatusBadge status={item.status === "ACTIVE" ? "active" : "inactive"} /></TableCell></TableRow>)}</TableBody></Table></div> : <div className="mt-5"><EmptyState title="No menu performance data" description="Completed POS item sales will appear here." /></div>}</ContentCard>; }

function BranchReport({ data }) { return <ContentCard><SectionHeader title="Branch comparison" description="Compare completed sales for the selected reporting period." /><div className="mt-5"><Table><TableHeader><TableRow><TableCell as="th">Metric</TableCell>{data.branchComparison.map((branch) => <TableCell key={branch.id} as="th">{branch.name}</TableCell>)}</TableRow></TableHeader><TableBody>{[["Total sales", (branch) => money(branch.totalSales)], ["Transactions", (branch) => branch.transactions], ["Average transaction", (branch) => money(branch.averageTransaction)]].map(([label, value]) => <TableRow key={label}><TableCell className="font-semibold text-slate-900">{label}</TableCell>{data.branchComparison.map((branch) => <TableCell key={branch.id}>{value(branch)}</TableCell>)}</TableRow>)}</TableBody></Table></div>{!data.branchComparison.some((branch) => branch.transactions) && <div className="mt-5"><EmptyState title="No branch report data" description="Completed POS transactions are needed for branch comparison." /></div>}</ContentCard>; }

function InventoryReport({ data }) { return <><ResponsiveGrid columns="three"><StatCard label="Inventory items" value={data.inventorySummary.totalItems} icon={Boxes} /><StatCard label="Low-stock items" value={data.inventorySummary.lowStock} icon={Boxes} className="border-amber-200" /><StatCard label="Out-of-stock items" value={data.inventorySummary.outOfStock} icon={Boxes} className="border-rose-200" /></ResponsiveGrid><ContentCard className="mt-7"><SectionHeader title="Inventory summary" description="Current branch inventory status and value from the operational mock inventory." /><div className="mt-5"><Table><TableHeader><TableRow><TableCell as="th">Item</TableCell><TableCell as="th">Branch</TableCell><TableCell as="th">Current quantity</TableCell><TableCell as="th">Status</TableCell><TableCell as="th">Inventory value</TableCell></TableRow></TableHeader><TableBody>{data.inventorySummary.items.map((item) => <TableRow key={`${item.branchId}-${item.id}`}><TableCell className="font-semibold text-slate-900">{item.name}</TableCell><TableCell>{item.branchName}</TableCell><TableCell>{item.currentQuantity} {item.unit}</TableCell><TableCell><StatusBadge status={item.status} /></TableCell><TableCell>{money(item.currentQuantity * item.costPerUnit)}</TableCell></TableRow>)}</TableBody></Table></div></ContentCard></>; }

export default function Reports() {
  const [period, setPeriod] = useState("MONTH"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [branchId, setBranchId] = useState("ALL"); const [reportType, setReportType] = useState("SALES"); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refreshReports = async () => {
    setLoading(true);
    try {
      const nextData = await getReportsData({ period, from, to, branchId });
      setData(nextData);
      setError("");
      return nextData;
    } catch (loadError) {
      setError(loadError.message);
      return null;
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => {
    let isMounted = true;
    const load = async () => {
      if (!isMounted) return;
      await refreshReports();
    };

    void load();
    return () => {
      isMounted = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [period, from, to, branchId]);
  const reset = () => { setPeriod("MONTH"); setFrom(""); setTo(""); setBranchId("ALL"); };
  const title = useMemo(() => reportTypes[reportType], [reportType]);
  if (loading) return <PageContainer><LoadingState label="Loading reports" /></PageContainer>;
  if (error || !data) return <PageContainer><ErrorState title="Reports unavailable" description={error} action={<Button onClick={() => { void refreshReports(); }}>Try again</Button>} /></PageContainer>;
  return <PageContainer><PageHeader title="Reports" description="Detailed sales, transaction, and business performance reports." meta={<Badge variant="purple">Owner only</Badge>} /><FilterBar className="mt-7 items-end"><label className="flex-1 text-sm font-medium text-slate-800">Period<Select value={period} onChange={(event) => setPeriod(event.target.value)} aria-label="Report date range" className="mt-1"><option value="TODAY">Today</option><option value="WEEK">This week</option><option value="MONTH">This month</option><option value="CUSTOM">Custom range</option></Select></label>{period === "CUSTOM" && <><label className="flex-1 text-sm font-medium text-slate-800">From<Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} aria-label="Report start date" className="mt-1" /></label><label className="flex-1 text-sm font-medium text-slate-800">To<Input type="date" value={to} onChange={(event) => setTo(event.target.value)} aria-label="Report end date" className="mt-1" /></label></>}<label className="flex-1 text-sm font-medium text-slate-800">Branch<Select value={branchId} onChange={(event) => setBranchId(event.target.value)} aria-label="Report branch" className="mt-1"><option value="ALL">All branches</option>{data.branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></label><label className="flex-1 text-sm font-medium text-slate-800">Report type<Select value={reportType} onChange={(event) => setReportType(event.target.value)} aria-label="Report type" className="mt-1">{Object.entries(reportTypes).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><Button variant="ghost" onClick={reset}>Reset</Button></FilterBar><div className="mt-7"><SectionHeader title={title} description="Derived from the existing Taste It mock records." />{reportType === "SALES" && <div className="mt-5"><SalesReport data={data} /></div>}{reportType === "TRANSACTIONS" && <div className="mt-5"><TransactionsReport data={data} /></div>}{reportType === "MENU" && <div className="mt-5"><MenuReport data={data} /></div>}{reportType === "BRANCH" && <div className="mt-5"><BranchReport data={data} /></div>}{reportType === "INVENTORY" && <div className="mt-5"><InventoryReport data={data} /></div>}</div></PageContainer>;
}
